name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.17]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: |
          AFFECTED=`npx nx affected:apps --plain --base=origin/master`;
          echo "Building: ${AFFECTED}"
          for app in ${AFFECTED}; do
            echo "building ${app}";
            npm run build:${app};
          done;
      - run: npm run affected:lint --base=origin/master
      - run: npm run test
        env:
          CI: true
      - run: |
          # Generate default json for bundlesize
          # This is a quick hack to get bundlesize AND affected build working.
          # Maintain this script to keep checking new apps.
          mkdir -p dist/apps/delivery \
                   dist/apps/catalog-marketplace \
                   dist/apps/catalog-dashboard \
                   dist/apps/backend-functions \
                   dist/apps/movie-financing
          touch ./dist/apps/main.dummy.js \
                ./dist/apps/delivery/main.dummy.js \
                ./dist/apps/catalog-marketplace/main.dummy.js \
                ./dist/apps/catalog-dashboard/main.dummy.js \
                ./dist/apps/backend-functions/main.dummy.js \
                ./dist/apps/movie-financing/main.dummy.js \
          npm run bundlesize
      - run: |
          if [ "${CIRCLE_BRANCH}" = "production" ] || [ "${CIRCLE_BRANCH}" = "master" ]; then
            npm run build:all;
            curl -X POST "${ZAPPIER_WEBHOOK}" --header "Build-number:${CIRCLE_BUILD_NUM}" --header "Branch:${CIRCLE_BRANCH}" --header  "Date:`date "+%D"`" --header  Main-size:`cat ./dist/apps/main**.js | wc -c` --header  Delivery-size:`cat ./dist/apps/delivery/main**.js | wc -c` --header  Marketplace-size:`cat ./dist/apps/catalog-marketplace/main**.js | wc -c` --header  Dashboard-size:`cat ./dist/apps/catalog-dashboard/main**.js | wc -c` --header  Movie-financing-size:`cat ./dist/apps/movie-financing/main**.js | wc -c` --header  Functions-size:`cat ./dist/apps/backend-functions/main**.js | wc -c`;
          fi
